// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma contract emit'.
// To regenerate, run: prisma contract emit
import type { CodecTypes as SqliteTypes } from '@prisma/orm-sqlite/adapter/codec-types';

import type {
  ContractWithTypeMaps,
  RelationKeys,
  TypeMaps as TypeMapsType,
} from '@prisma/orm-sqlite/family-contract/types';
import type {
  Contract as ContractType,
  ExecutionHashBase,
  NamespaceId,
  ProfileHashBase,
  StorageHashBase,
} from '@prisma/orm-sqlite/contract/types';

export type StorageHash =
  StorageHashBase<'4de5b1e9dbd30bde4f9d75b24eaef329b9fbf6914fdfa951e90ff5595442d407'>;
export type ExecutionHash = ExecutionHashBase<string>;
export type ProfileHash =
  ProfileHashBase<'260b8608d1aacaf1f690779a6cff39a12947c599597c5ba464ca75b9e775df53'>;

export type CodecTypes = SqliteTypes;
export type LaneCodecTypes = CodecTypes;
export type QueryOperationTypes = Record<string, never>;
export type AggregateTypes = {
  readonly avg: {
    readonly byCodec: {
      readonly 'sql/float@1': { readonly output: 'sqlite/real@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sqlite/real@1'; readonly nullable: true };
      readonly 'sqlite/bigint@1': { readonly output: 'sqlite/real@1'; readonly nullable: true };
      readonly 'sqlite/bigintnumber@1': {
        readonly output: 'sqlite/real@1';
        readonly nullable: true;
      };
      readonly 'sqlite/integer@1': { readonly output: 'sqlite/real@1'; readonly nullable: true };
      readonly 'sqlite/real@1': { readonly output: 'sqlite/real@1'; readonly nullable: true };
    };
  };
  readonly count: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'sqlite/bigintnumber@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'sqlite/bigintnumber@1'; readonly nullable: false };
  };
  readonly countBigInt: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'sqlite/bigint@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'sqlite/bigint@1'; readonly nullable: false };
  };
  readonly max: {
    readonly byCodec: {
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sqlite/bigint@1': { readonly output: 'sqlite/bigint@1'; readonly nullable: true };
      readonly 'sqlite/bigintnumber@1': {
        readonly output: 'sqlite/bigintnumber@1';
        readonly nullable: true;
      };
      readonly 'sqlite/blob@1': { readonly output: 'sqlite/blob@1'; readonly nullable: true };
      readonly 'sqlite/datetime@1': {
        readonly output: 'sqlite/datetime@1';
        readonly nullable: true;
      };
      readonly 'sqlite/integer@1': { readonly output: 'sqlite/integer@1'; readonly nullable: true };
      readonly 'sqlite/json@1': { readonly output: 'sqlite/json@1'; readonly nullable: true };
      readonly 'sqlite/real@1': { readonly output: 'sqlite/real@1'; readonly nullable: true };
      readonly 'sqlite/text@1': { readonly output: 'sqlite/text@1'; readonly nullable: true };
    };
  };
  readonly min: {
    readonly byCodec: {
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sqlite/bigint@1': { readonly output: 'sqlite/bigint@1'; readonly nullable: true };
      readonly 'sqlite/bigintnumber@1': {
        readonly output: 'sqlite/bigintnumber@1';
        readonly nullable: true;
      };
      readonly 'sqlite/blob@1': { readonly output: 'sqlite/blob@1'; readonly nullable: true };
      readonly 'sqlite/datetime@1': {
        readonly output: 'sqlite/datetime@1';
        readonly nullable: true;
      };
      readonly 'sqlite/integer@1': { readonly output: 'sqlite/integer@1'; readonly nullable: true };
      readonly 'sqlite/json@1': { readonly output: 'sqlite/json@1'; readonly nullable: true };
      readonly 'sqlite/real@1': { readonly output: 'sqlite/real@1'; readonly nullable: true };
      readonly 'sqlite/text@1': { readonly output: 'sqlite/text@1'; readonly nullable: true };
    };
  };
  readonly sum: {
    readonly byCodec: {
      readonly 'sql/float@1': { readonly output: 'sqlite/real@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sqlite/bigintnumber@1'; readonly nullable: true };
      readonly 'sqlite/bigint@1': {
        readonly output: 'sqlite/bigintnumber@1';
        readonly nullable: true;
      };
      readonly 'sqlite/bigintnumber@1': {
        readonly output: 'sqlite/bigintnumber@1';
        readonly nullable: true;
      };
      readonly 'sqlite/integer@1': {
        readonly output: 'sqlite/bigintnumber@1';
        readonly nullable: true;
      };
      readonly 'sqlite/real@1': { readonly output: 'sqlite/real@1'; readonly nullable: true };
    };
  };
  readonly sumBigInt: {
    readonly byCodec: {
      readonly 'sql/int@1': { readonly output: 'sqlite/bigint@1'; readonly nullable: true };
      readonly 'sqlite/bigint@1': { readonly output: 'sqlite/bigint@1'; readonly nullable: true };
      readonly 'sqlite/bigintnumber@1': {
        readonly output: 'sqlite/bigint@1';
        readonly nullable: true;
      };
      readonly 'sqlite/integer@1': { readonly output: 'sqlite/bigint@1'; readonly nullable: true };
    };
  };
};
type DefaultLiteralValue<CodecId extends string, Encoded> = CodecId extends keyof CodecTypes
  ? Encoded extends CodecTypes[CodecId]['json']
    ? Encoded
    : CodecTypes[CodecId]['json']
  : Encoded;

export type FieldOutputTypes = {
  readonly __unbound__: {
    readonly OperationalSetting: {
      readonly key: CodecTypes['sqlite/text@1']['output'];
      readonly value: CodecTypes['sqlite/text@1']['output'];
    };
  };
};
export type FieldInputTypes = {
  readonly __unbound__: {
    readonly OperationalSetting: {
      readonly key: CodecTypes['sqlite/text@1']['input'];
      readonly value: CodecTypes['sqlite/text@1']['input'];
    };
  };
};
export type StorageColumnTypes = {
  readonly __unbound__: {
    readonly operational_settings: {
      readonly key: CodecTypes['sqlite/text@1']['output'];
      readonly value: CodecTypes['sqlite/text@1']['output'];
    };
  };
};
export type StorageColumnInputTypes = {
  readonly __unbound__: {
    readonly operational_settings: {
      readonly key: CodecTypes['sqlite/text@1']['input'];
      readonly value: CodecTypes['sqlite/text@1']['input'];
    };
  };
};

export namespace Models {
  export type OperationalSetting = {
    key: CodecTypes['sqlite/text@1']['output'];
    value: CodecTypes['sqlite/text@1']['output'];
    readonly [RelationKeys]?: never;
  };
}

export declare const models: {
  OperationalSetting: Models.OperationalSetting;
};

export type TypeMaps = TypeMapsType<
  CodecTypes,
  QueryOperationTypes,
  FieldOutputTypes,
  FieldInputTypes,
  StorageColumnTypes,
  StorageColumnInputTypes,
  AggregateTypes
>;

type ContractBase = Omit<
  ContractType<{
    readonly namespaces: {
      readonly __unbound__: {
        readonly id: '__unbound__';
        readonly kind: 'sqlite-namespace';
        readonly entries: {
          readonly table: {
            readonly operational_settings: {
              columns: {
                readonly key: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                };
                readonly value: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['key'] };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
          };
        };
      };
    };
    readonly storageHash: StorageHash;
  }>,
  'roots' | 'domain'
> & {
  readonly target: 'sqlite';
  readonly targetFamily: 'sql';
  readonly roots: {
    readonly operational_settings: {
      readonly namespace: '__unbound__' & NamespaceId;
      readonly model: 'OperationalSetting';
    };
  };
  readonly domain: {
    readonly namespaces: {
      readonly __unbound__: {
        readonly models: {
          readonly OperationalSetting: {
            readonly fields: {
              readonly key: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly value: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: {
              readonly table: 'operational_settings';
              readonly namespaceId: '__unbound__';
              readonly fields: {
                readonly key: { readonly column: 'key' };
                readonly value: { readonly column: 'value' };
              };
            };
          };
        };
      };
    };
  };
  readonly capabilities: {
    readonly sql: {
      readonly foreignKeys: true;
      readonly insertOnConflictSkip: true;
      readonly insertOnConflictWithoutTarget: true;
      readonly jsonAgg: true;
      readonly limit: true;
      readonly orderBy: true;
      readonly returning: true;
    };
  };
  readonly extensions: {};
  readonly meta: {};

  readonly profileHash: ProfileHash;
};

export type Contract = ContractWithTypeMaps<ContractBase, TypeMaps>;

export type Namespaces = Contract['storage']['namespaces'];
