// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma contract emit'.
// To regenerate, run: prisma contract emit
import type { CodecTypes as SqliteTypes } from '@prisma/orm-sqlite/adapter/codec-types';

import type {
  ContractWithTypeMaps,
  RelationKeys,
  TypeMaps as TypeMapsType,
} from '@prisma/orm-sqlite/family-contract/types';
import type {
  Contract as ContractType,
  ExecutionHashBase,
  NamespaceId,
  ProfileHashBase,
  StorageHashBase,
} from '@prisma/orm-sqlite/contract/types';

export type StorageHash =
  StorageHashBase<'d6c5331639e413b91e7583cb56357579a5a970efc2ee7aff52dbcab5ec17805d'>;
export type ExecutionHash =
  ExecutionHashBase<'d0f9c05261c50d2b6e441b777efd3ad370e00370c1751368fdaddb0bb974a237'>;
export type ProfileHash =
  ProfileHashBase<'260b8608d1aacaf1f690779a6cff39a12947c599597c5ba464ca75b9e775df53'>;

export type CodecTypes = SqliteTypes;
export type LaneCodecTypes = CodecTypes;
export type QueryOperationTypes = Record<string, never>;
export type AggregateTypes = {
  readonly avg: {
    readonly byCodec: {
      readonly 'sql/float@1': { readonly output: 'sqlite/real@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sqlite/real@1'; readonly nullable: true };
      readonly 'sqlite/bigint@1': { readonly output: 'sqlite/real@1'; readonly nullable: true };
      readonly 'sqlite/bigintnumber@1': {
        readonly output: 'sqlite/real@1';
        readonly nullable: true;
      };
      readonly 'sqlite/integer@1': { readonly output: 'sqlite/real@1'; readonly nullable: true };
      readonly 'sqlite/real@1': { readonly output: 'sqlite/real@1'; readonly nullable: true };
    };
  };
  readonly count: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'sqlite/bigintnumber@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'sqlite/bigintnumber@1'; readonly nullable: false };
  };
  readonly countBigInt: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'sqlite/bigint@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'sqlite/bigint@1'; readonly nullable: false };
  };
  readonly max: {
    readonly byCodec: {
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sqlite/bigint@1': { readonly output: 'sqlite/bigint@1'; readonly nullable: true };
      readonly 'sqlite/bigintnumber@1': {
        readonly output: 'sqlite/bigintnumber@1';
        readonly nullable: true;
      };
      readonly 'sqlite/blob@1': { readonly output: 'sqlite/blob@1'; readonly nullable: true };
      readonly 'sqlite/datetime@1': {
        readonly output: 'sqlite/datetime@1';
        readonly nullable: true;
      };
      readonly 'sqlite/integer@1': { readonly output: 'sqlite/integer@1'; readonly nullable: true };
      readonly 'sqlite/json@1': { readonly output: 'sqlite/json@1'; readonly nullable: true };
      readonly 'sqlite/real@1': { readonly output: 'sqlite/real@1'; readonly nullable: true };
      readonly 'sqlite/text@1': { readonly output: 'sqlite/text@1'; readonly nullable: true };
    };
  };
  readonly min: {
    readonly byCodec: {
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sqlite/bigint@1': { readonly output: 'sqlite/bigint@1'; readonly nullable: true };
      readonly 'sqlite/bigintnumber@1': {
        readonly output: 'sqlite/bigintnumber@1';
        readonly nullable: true;
      };
      readonly 'sqlite/blob@1': { readonly output: 'sqlite/blob@1'; readonly nullable: true };
      readonly 'sqlite/datetime@1': {
        readonly output: 'sqlite/datetime@1';
        readonly nullable: true;
      };
      readonly 'sqlite/integer@1': { readonly output: 'sqlite/integer@1'; readonly nullable: true };
      readonly 'sqlite/json@1': { readonly output: 'sqlite/json@1'; readonly nullable: true };
      readonly 'sqlite/real@1': { readonly output: 'sqlite/real@1'; readonly nullable: true };
      readonly 'sqlite/text@1': { readonly output: 'sqlite/text@1'; readonly nullable: true };
    };
  };
  readonly sum: {
    readonly byCodec: {
      readonly 'sql/float@1': { readonly output: 'sqlite/real@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sqlite/bigintnumber@1'; readonly nullable: true };
      readonly 'sqlite/bigint@1': {
        readonly output: 'sqlite/bigintnumber@1';
        readonly nullable: true;
      };
      readonly 'sqlite/bigintnumber@1': {
        readonly output: 'sqlite/bigintnumber@1';
        readonly nullable: true;
      };
      readonly 'sqlite/integer@1': {
        readonly output: 'sqlite/bigintnumber@1';
        readonly nullable: true;
      };
      readonly 'sqlite/real@1': { readonly output: 'sqlite/real@1'; readonly nullable: true };
    };
  };
  readonly sumBigInt: {
    readonly byCodec: {
      readonly 'sql/int@1': { readonly output: 'sqlite/bigint@1'; readonly nullable: true };
      readonly 'sqlite/bigint@1': { readonly output: 'sqlite/bigint@1'; readonly nullable: true };
      readonly 'sqlite/bigintnumber@1': {
        readonly output: 'sqlite/bigint@1';
        readonly nullable: true;
      };
      readonly 'sqlite/integer@1': { readonly output: 'sqlite/bigint@1'; readonly nullable: true };
    };
  };
};
type DefaultLiteralValue<CodecId extends string, Encoded> = CodecId extends keyof CodecTypes
  ? Encoded extends CodecTypes[CodecId]['json']
    ? Encoded
    : CodecTypes[CodecId]['json']
  : Encoded;

export type FieldOutputTypes = {
  readonly __unbound__: {
    readonly Library: {
      readonly id: CodecTypes['sql/char@1']['output'];
      readonly name: CodecTypes['sqlite/text@1']['output'];
    };
    readonly Outbox: {
      readonly attempted: CodecTypes['sqlite/text@1']['output'];
      readonly confirmedAt: CodecTypes['sqlite/text@1']['output'];
      readonly error: CodecTypes['sqlite/text@1']['output'];
      readonly id: CodecTypes['sql/char@1']['output'];
      readonly nextAt: CodecTypes['sqlite/text@1']['output'];
      readonly payload: CodecTypes['sqlite/text@1']['output'];
      readonly remoteId: CodecTypes['sqlite/text@1']['output'];
      readonly state: CodecTypes['sqlite/text@1']['output'];
    };
    readonly Session: {
      readonly csrf: CodecTypes['sqlite/text@1']['output'];
      readonly expiresAt: CodecTypes['sqlite/text@1']['output'];
      readonly id: CodecTypes['sql/char@1']['output'];
    };
    readonly Setting: {
      readonly id: CodecTypes['sql/char@1']['output'];
      readonly value: CodecTypes['sqlite/text@1']['output'];
    };
    readonly Slot: {
      readonly id: CodecTypes['sql/char@1']['output'];
      readonly name: CodecTypes['sqlite/text@1']['output'];
      readonly time: CodecTypes['sqlite/text@1']['output'];
    };
  };
};
export type FieldInputTypes = {
  readonly __unbound__: {
    readonly Library: {
      readonly id: CodecTypes['sql/char@1']['input'];
      readonly name: CodecTypes['sqlite/text@1']['input'];
    };
    readonly Outbox: {
      readonly attempted: CodecTypes['sqlite/text@1']['input'];
      readonly confirmedAt: CodecTypes['sqlite/text@1']['input'];
      readonly error: CodecTypes['sqlite/text@1']['input'];
      readonly id: CodecTypes['sql/char@1']['input'];
      readonly nextAt: CodecTypes['sqlite/text@1']['input'];
      readonly payload: CodecTypes['sqlite/text@1']['input'];
      readonly remoteId: CodecTypes['sqlite/text@1']['input'];
      readonly state: CodecTypes['sqlite/text@1']['input'];
    };
    readonly Session: {
      readonly csrf: CodecTypes['sqlite/text@1']['input'];
      readonly expiresAt: CodecTypes['sqlite/text@1']['input'];
      readonly id: CodecTypes['sql/char@1']['input'];
    };
    readonly Setting: {
      readonly id: CodecTypes['sql/char@1']['input'];
      readonly value: CodecTypes['sqlite/text@1']['input'];
    };
    readonly Slot: {
      readonly id: CodecTypes['sql/char@1']['input'];
      readonly name: CodecTypes['sqlite/text@1']['input'];
      readonly time: CodecTypes['sqlite/text@1']['input'];
    };
  };
};
export type StorageColumnTypes = {
  readonly __unbound__: {
    readonly library: {
      readonly id: CodecTypes['sql/char@1']['output'];
      readonly name: CodecTypes['sqlite/text@1']['output'];
    };
    readonly outbox: {
      readonly attempted: CodecTypes['sqlite/text@1']['output'];
      readonly confirmedAt: CodecTypes['sqlite/text@1']['output'];
      readonly error: CodecTypes['sqlite/text@1']['output'];
      readonly id: CodecTypes['sql/char@1']['output'];
      readonly nextAt: CodecTypes['sqlite/text@1']['output'];
      readonly payload: CodecTypes['sqlite/text@1']['output'];
      readonly remoteId: CodecTypes['sqlite/text@1']['output'];
      readonly state: CodecTypes['sqlite/text@1']['output'];
    };
    readonly session: {
      readonly csrf: CodecTypes['sqlite/text@1']['output'];
      readonly expiresAt: CodecTypes['sqlite/text@1']['output'];
      readonly id: CodecTypes['sql/char@1']['output'];
    };
    readonly setting: {
      readonly id: CodecTypes['sql/char@1']['output'];
      readonly value: CodecTypes['sqlite/text@1']['output'];
    };
    readonly slot: {
      readonly id: CodecTypes['sql/char@1']['output'];
      readonly name: CodecTypes['sqlite/text@1']['output'];
      readonly time: CodecTypes['sqlite/text@1']['output'];
    };
  };
};
export type StorageColumnInputTypes = {
  readonly __unbound__: {
    readonly library: {
      readonly id: CodecTypes['sql/char@1']['input'];
      readonly name: CodecTypes['sqlite/text@1']['input'];
    };
    readonly outbox: {
      readonly attempted: CodecTypes['sqlite/text@1']['input'];
      readonly confirmedAt: CodecTypes['sqlite/text@1']['input'];
      readonly error: CodecTypes['sqlite/text@1']['input'];
      readonly id: CodecTypes['sql/char@1']['input'];
      readonly nextAt: CodecTypes['sqlite/text@1']['input'];
      readonly payload: CodecTypes['sqlite/text@1']['input'];
      readonly remoteId: CodecTypes['sqlite/text@1']['input'];
      readonly state: CodecTypes['sqlite/text@1']['input'];
    };
    readonly session: {
      readonly csrf: CodecTypes['sqlite/text@1']['input'];
      readonly expiresAt: CodecTypes['sqlite/text@1']['input'];
      readonly id: CodecTypes['sql/char@1']['input'];
    };
    readonly setting: {
      readonly id: CodecTypes['sql/char@1']['input'];
      readonly value: CodecTypes['sqlite/text@1']['input'];
    };
    readonly slot: {
      readonly id: CodecTypes['sql/char@1']['input'];
      readonly name: CodecTypes['sqlite/text@1']['input'];
      readonly time: CodecTypes['sqlite/text@1']['input'];
    };
  };
};

export namespace Models {
  export type Library = {
    id: CodecTypes['sql/char@1']['output'];
    name: CodecTypes['sqlite/text@1']['output'];
    readonly [RelationKeys]?: never;
  };
  export type Outbox = {
    attempted: CodecTypes['sqlite/text@1']['output'];
    confirmedAt: CodecTypes['sqlite/text@1']['output'];
    error: CodecTypes['sqlite/text@1']['output'];
    id: CodecTypes['sql/char@1']['output'];
    nextAt: CodecTypes['sqlite/text@1']['output'];
    payload: CodecTypes['sqlite/text@1']['output'];
    remoteId: CodecTypes['sqlite/text@1']['output'];
    state: CodecTypes['sqlite/text@1']['output'];
    readonly [RelationKeys]?: never;
  };
  export type Session = {
    csrf: CodecTypes['sqlite/text@1']['output'];
    expiresAt: CodecTypes['sqlite/text@1']['output'];
    id: CodecTypes['sql/char@1']['output'];
    readonly [RelationKeys]?: never;
  };
  export type Setting = {
    id: CodecTypes['sql/char@1']['output'];
    value: CodecTypes['sqlite/text@1']['output'];
    readonly [RelationKeys]?: never;
  };
  export type Slot = {
    id: CodecTypes['sql/char@1']['output'];
    name: CodecTypes['sqlite/text@1']['output'];
    time: CodecTypes['sqlite/text@1']['output'];
    readonly [RelationKeys]?: never;
  };
}

export declare const models: {
  Library: Models.Library;
  Outbox: Models.Outbox;
  Session: Models.Session;
  Setting: Models.Setting;
  Slot: Models.Slot;
};

export type TypeMaps = TypeMapsType<
  CodecTypes,
  QueryOperationTypes,
  FieldOutputTypes,
  FieldInputTypes,
  StorageColumnTypes,
  StorageColumnInputTypes,
  AggregateTypes
>;

type ContractBase = Omit<
  ContractType<{
    readonly namespaces: {
      readonly __unbound__: {
        readonly id: '__unbound__';
        readonly kind: 'sqlite-namespace';
        readonly entries: {
          readonly table: {
            readonly library: {
              columns: {
                readonly id: {
                  readonly nativeType: 'character';
                  readonly codecId: 'sql/char@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly length: 36 };
                };
                readonly name: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly outbox: {
              columns: {
                readonly attempted: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                };
                readonly confirmedAt: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                };
                readonly error: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                };
                readonly id: {
                  readonly nativeType: 'character';
                  readonly codecId: 'sql/char@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly length: 36 };
                };
                readonly nextAt: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                };
                readonly payload: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                };
                readonly remoteId: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                };
                readonly state: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly session: {
              columns: {
                readonly csrf: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                };
                readonly expiresAt: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                };
                readonly id: {
                  readonly nativeType: 'character';
                  readonly codecId: 'sql/char@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly length: 36 };
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly setting: {
              columns: {
                readonly id: {
                  readonly nativeType: 'character';
                  readonly codecId: 'sql/char@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly length: 36 };
                };
                readonly value: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly slot: {
              columns: {
                readonly id: {
                  readonly nativeType: 'character';
                  readonly codecId: 'sql/char@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly length: 36 };
                };
                readonly name: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                };
                readonly time: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
          };
        };
      };
    };
    readonly storageHash: StorageHash;
  }>,
  'roots' | 'domain'
> & {
  readonly target: 'sqlite';
  readonly targetFamily: 'sql';
  readonly roots: {
    readonly library: {
      readonly namespace: '__unbound__' & NamespaceId;
      readonly model: 'Library';
    };
    readonly outbox: { readonly namespace: '__unbound__' & NamespaceId; readonly model: 'Outbox' };
    readonly session: {
      readonly namespace: '__unbound__' & NamespaceId;
      readonly model: 'Session';
    };
    readonly setting: {
      readonly namespace: '__unbound__' & NamespaceId;
      readonly model: 'Setting';
    };
    readonly slot: { readonly namespace: '__unbound__' & NamespaceId; readonly model: 'Slot' };
  };
  readonly domain: {
    readonly namespaces: {
      readonly __unbound__: {
        readonly models: {
          readonly Library: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/char@1';
                  readonly typeParams: { readonly length: 36 };
                };
              };
              readonly name: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: {
              readonly table: 'library';
              readonly namespaceId: '__unbound__';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly name: { readonly column: 'name' };
              };
            };
          };
          readonly Outbox: {
            readonly fields: {
              readonly attempted: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly confirmedAt: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly error: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly id: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/char@1';
                  readonly typeParams: { readonly length: 36 };
                };
              };
              readonly nextAt: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly payload: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly remoteId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly state: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: {
              readonly table: 'outbox';
              readonly namespaceId: '__unbound__';
              readonly fields: {
                readonly attempted: { readonly column: 'attempted' };
                readonly confirmedAt: { readonly column: 'confirmedAt' };
                readonly error: { readonly column: 'error' };
                readonly id: { readonly column: 'id' };
                readonly nextAt: { readonly column: 'nextAt' };
                readonly payload: { readonly column: 'payload' };
                readonly remoteId: { readonly column: 'remoteId' };
                readonly state: { readonly column: 'state' };
              };
            };
          };
          readonly Session: {
            readonly fields: {
              readonly csrf: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly expiresAt: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly id: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/char@1';
                  readonly typeParams: { readonly length: 36 };
                };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: {
              readonly table: 'session';
              readonly namespaceId: '__unbound__';
              readonly fields: {
                readonly csrf: { readonly column: 'csrf' };
                readonly expiresAt: { readonly column: 'expiresAt' };
                readonly id: { readonly column: 'id' };
              };
            };
          };
          readonly Setting: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/char@1';
                  readonly typeParams: { readonly length: 36 };
                };
              };
              readonly value: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: {
              readonly table: 'setting';
              readonly namespaceId: '__unbound__';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly value: { readonly column: 'value' };
              };
            };
          };
          readonly Slot: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/char@1';
                  readonly typeParams: { readonly length: 36 };
                };
              };
              readonly name: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly time: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: {
              readonly table: 'slot';
              readonly namespaceId: '__unbound__';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly name: { readonly column: 'name' };
                readonly time: { readonly column: 'time' };
              };
            };
          };
        };
      };
    };
  };
  readonly capabilities: {
    readonly sql: {
      readonly foreignKeys: true;
      readonly insertOnConflictSkip: true;
      readonly insertOnConflictWithoutTarget: true;
      readonly jsonAgg: true;
      readonly limit: true;
      readonly orderBy: true;
      readonly returning: true;
    };
  };
  readonly extensions: {};
  readonly execution: {
    readonly executionHash: ExecutionHash;
    readonly mutations: {
      readonly defaults: readonly [
        {
          readonly onCreate: { readonly id: 'uuidv4'; readonly kind: 'generator' };
          readonly ref: {
            readonly entry: 'library';
            readonly field: 'id';
            readonly namespace: '__unbound__';
          };
        },
        {
          readonly onCreate: { readonly id: 'uuidv4'; readonly kind: 'generator' };
          readonly ref: {
            readonly entry: 'outbox';
            readonly field: 'id';
            readonly namespace: '__unbound__';
          };
        },
        {
          readonly onCreate: { readonly id: 'uuidv4'; readonly kind: 'generator' };
          readonly ref: {
            readonly entry: 'session';
            readonly field: 'id';
            readonly namespace: '__unbound__';
          };
        },
        {
          readonly onCreate: { readonly id: 'uuidv4'; readonly kind: 'generator' };
          readonly ref: {
            readonly entry: 'setting';
            readonly field: 'id';
            readonly namespace: '__unbound__';
          };
        },
        {
          readonly onCreate: { readonly id: 'uuidv4'; readonly kind: 'generator' };
          readonly ref: {
            readonly entry: 'slot';
            readonly field: 'id';
            readonly namespace: '__unbound__';
          };
        },
      ];
    };
  };
  readonly meta: {};

  readonly profileHash: ProfileHash;
};

export type Contract = ContractWithTypeMaps<ContractBase, TypeMaps>;

export type Namespaces = Contract['storage']['namespaces'];
