// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma contract emit'.
// To regenerate, run: prisma contract emit
import type { CodecTypes as SqliteTypes } from '@prisma/orm-sqlite/adapter/codec-types';

import type {
  ContractWithTypeMaps,
  RelationKeys,
  TypeMaps as TypeMapsType,
} from '@prisma/orm-sqlite/family-contract/types';
import type {
  Contract as ContractType,
  ExecutionHashBase,
  NamespaceId,
  ProfileHashBase,
  StorageHashBase,
} from '@prisma/orm-sqlite/contract/types';

export type StorageHash =
  StorageHashBase<'f98afee84feb956a923f4bc8c8d94286a3f663c4dcdf6d96bdc1166cb71a6382'>;
export type ExecutionHash = ExecutionHashBase<string>;
export type ProfileHash =
  ProfileHashBase<'260b8608d1aacaf1f690779a6cff39a12947c599597c5ba464ca75b9e775df53'>;

export type CodecTypes = SqliteTypes;
export type LaneCodecTypes = CodecTypes;
export type QueryOperationTypes = Record<string, never>;
export type AggregateTypes = {
  readonly avg: {
    readonly byCodec: {
      readonly 'sql/float@1': { readonly output: 'sqlite/real@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sqlite/real@1'; readonly nullable: true };
      readonly 'sqlite/bigint@1': { readonly output: 'sqlite/real@1'; readonly nullable: true };
      readonly 'sqlite/bigintnumber@1': {
        readonly output: 'sqlite/real@1';
        readonly nullable: true;
      };
      readonly 'sqlite/integer@1': { readonly output: 'sqlite/real@1'; readonly nullable: true };
      readonly 'sqlite/real@1': { readonly output: 'sqlite/real@1'; readonly nullable: true };
    };
  };
  readonly count: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'sqlite/bigintnumber@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'sqlite/bigintnumber@1'; readonly nullable: false };
  };
  readonly countBigInt: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'sqlite/bigint@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'sqlite/bigint@1'; readonly nullable: false };
  };
  readonly max: {
    readonly byCodec: {
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sqlite/bigint@1': { readonly output: 'sqlite/bigint@1'; readonly nullable: true };
      readonly 'sqlite/bigintnumber@1': {
        readonly output: 'sqlite/bigintnumber@1';
        readonly nullable: true;
      };
      readonly 'sqlite/blob@1': { readonly output: 'sqlite/blob@1'; readonly nullable: true };
      readonly 'sqlite/datetime@1': {
        readonly output: 'sqlite/datetime@1';
        readonly nullable: true;
      };
      readonly 'sqlite/integer@1': { readonly output: 'sqlite/integer@1'; readonly nullable: true };
      readonly 'sqlite/json@1': { readonly output: 'sqlite/json@1'; readonly nullable: true };
      readonly 'sqlite/real@1': { readonly output: 'sqlite/real@1'; readonly nullable: true };
      readonly 'sqlite/text@1': { readonly output: 'sqlite/text@1'; readonly nullable: true };
    };
  };
  readonly min: {
    readonly byCodec: {
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sqlite/bigint@1': { readonly output: 'sqlite/bigint@1'; readonly nullable: true };
      readonly 'sqlite/bigintnumber@1': {
        readonly output: 'sqlite/bigintnumber@1';
        readonly nullable: true;
      };
      readonly 'sqlite/blob@1': { readonly output: 'sqlite/blob@1'; readonly nullable: true };
      readonly 'sqlite/datetime@1': {
        readonly output: 'sqlite/datetime@1';
        readonly nullable: true;
      };
      readonly 'sqlite/integer@1': { readonly output: 'sqlite/integer@1'; readonly nullable: true };
      readonly 'sqlite/json@1': { readonly output: 'sqlite/json@1'; readonly nullable: true };
      readonly 'sqlite/real@1': { readonly output: 'sqlite/real@1'; readonly nullable: true };
      readonly 'sqlite/text@1': { readonly output: 'sqlite/text@1'; readonly nullable: true };
    };
  };
  readonly sum: {
    readonly byCodec: {
      readonly 'sql/float@1': { readonly output: 'sqlite/real@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sqlite/bigintnumber@1'; readonly nullable: true };
      readonly 'sqlite/bigint@1': {
        readonly output: 'sqlite/bigintnumber@1';
        readonly nullable: true;
      };
      readonly 'sqlite/bigintnumber@1': {
        readonly output: 'sqlite/bigintnumber@1';
        readonly nullable: true;
      };
      readonly 'sqlite/integer@1': {
        readonly output: 'sqlite/bigintnumber@1';
        readonly nullable: true;
      };
      readonly 'sqlite/real@1': { readonly output: 'sqlite/real@1'; readonly nullable: true };
    };
  };
  readonly sumBigInt: {
    readonly byCodec: {
      readonly 'sql/int@1': { readonly output: 'sqlite/bigint@1'; readonly nullable: true };
      readonly 'sqlite/bigint@1': { readonly output: 'sqlite/bigint@1'; readonly nullable: true };
      readonly 'sqlite/bigintnumber@1': {
        readonly output: 'sqlite/bigint@1';
        readonly nullable: true;
      };
      readonly 'sqlite/integer@1': { readonly output: 'sqlite/bigint@1'; readonly nullable: true };
    };
  };
};
type DefaultLiteralValue<CodecId extends string, Encoded> = CodecId extends keyof CodecTypes
  ? Encoded extends CodecTypes[CodecId]['json']
    ? Encoded
    : CodecTypes[CodecId]['json']
  : Encoded;

export type FieldOutputTypes = {
  readonly __unbound__: {
    readonly IdempotentAction: {
      readonly attempts: CodecTypes['sqlite/integer@1']['output'];
      readonly createAttempted: CodecTypes['sqlite/integer@1']['output'];
      readonly kind: CodecTypes['sqlite/text@1']['output'];
      readonly lastError: CodecTypes['sqlite/text@1']['output'] | null;
      readonly nextAttempt: CodecTypes['sqlite/real@1']['output'];
      readonly payload: CodecTypes['sqlite/text@1']['output'];
      readonly remoteId: CodecTypes['sqlite/text@1']['output'] | null;
      readonly requestId: CodecTypes['sqlite/text@1']['output'];
      readonly responseJson: CodecTypes['sqlite/text@1']['output'] | null;
      readonly state: CodecTypes['sqlite/text@1']['output'];
      readonly taskKey: CodecTypes['sqlite/text@1']['output'] | null;
      readonly updatedAt: CodecTypes['sqlite/text@1']['output'];
    };
    readonly Kv: {
      readonly key: CodecTypes['sqlite/text@1']['output'];
      readonly value: CodecTypes['sqlite/text@1']['output'];
    };
    readonly MealLibraryEntry: {
      readonly createdAt: CodecTypes['sqlite/text@1']['output'];
      readonly id: CodecTypes['sqlite/text@1']['output'];
      readonly name: CodecTypes['sqlite/text@1']['output'];
      readonly position: CodecTypes['sqlite/integer@1']['output'];
    };
    readonly MealSlot: {
      readonly active: CodecTypes['sqlite/integer@1']['output'];
      readonly id: CodecTypes['sqlite/text@1']['output'];
      readonly name: CodecTypes['sqlite/text@1']['output'];
      readonly position: CodecTypes['sqlite/integer@1']['output'];
      readonly time: CodecTypes['sqlite/text@1']['output'];
      readonly timeAliases: CodecTypes['sqlite/text@1']['output'];
    };
    readonly ProjectTaskCache: {
      readonly projectId: CodecTypes['sqlite/text@1']['output'];
      readonly remoteId: CodecTypes['sqlite/text@1']['output'] | null;
      readonly seenAt: CodecTypes['sqlite/real@1']['output'];
      readonly taskJson: CodecTypes['sqlite/text@1']['output'];
      readonly taskKey: CodecTypes['sqlite/text@1']['output'];
    };
    readonly TaskTombstone: {
      readonly createdAt: CodecTypes['sqlite/real@1']['output'];
      readonly remoteId: CodecTypes['sqlite/text@1']['output'];
    };
  };
};
export type FieldInputTypes = {
  readonly __unbound__: {
    readonly IdempotentAction: {
      readonly attempts: CodecTypes['sqlite/integer@1']['input'];
      readonly createAttempted: CodecTypes['sqlite/integer@1']['input'];
      readonly kind: CodecTypes['sqlite/text@1']['input'];
      readonly lastError: CodecTypes['sqlite/text@1']['input'] | null;
      readonly nextAttempt: CodecTypes['sqlite/real@1']['input'];
      readonly payload: CodecTypes['sqlite/text@1']['input'];
      readonly remoteId: CodecTypes['sqlite/text@1']['input'] | null;
      readonly requestId: CodecTypes['sqlite/text@1']['input'];
      readonly responseJson: CodecTypes['sqlite/text@1']['input'] | null;
      readonly state: CodecTypes['sqlite/text@1']['input'];
      readonly taskKey: CodecTypes['sqlite/text@1']['input'] | null;
      readonly updatedAt: CodecTypes['sqlite/text@1']['input'];
    };
    readonly Kv: {
      readonly key: CodecTypes['sqlite/text@1']['input'];
      readonly value: CodecTypes['sqlite/text@1']['input'];
    };
    readonly MealLibraryEntry: {
      readonly createdAt: CodecTypes['sqlite/text@1']['input'];
      readonly id: CodecTypes['sqlite/text@1']['input'];
      readonly name: CodecTypes['sqlite/text@1']['input'];
      readonly position: CodecTypes['sqlite/integer@1']['input'];
    };
    readonly MealSlot: {
      readonly active: CodecTypes['sqlite/integer@1']['input'];
      readonly id: CodecTypes['sqlite/text@1']['input'];
      readonly name: CodecTypes['sqlite/text@1']['input'];
      readonly position: CodecTypes['sqlite/integer@1']['input'];
      readonly time: CodecTypes['sqlite/text@1']['input'];
      readonly timeAliases: CodecTypes['sqlite/text@1']['input'];
    };
    readonly ProjectTaskCache: {
      readonly projectId: CodecTypes['sqlite/text@1']['input'];
      readonly remoteId: CodecTypes['sqlite/text@1']['input'] | null;
      readonly seenAt: CodecTypes['sqlite/real@1']['input'];
      readonly taskJson: CodecTypes['sqlite/text@1']['input'];
      readonly taskKey: CodecTypes['sqlite/text@1']['input'];
    };
    readonly TaskTombstone: {
      readonly createdAt: CodecTypes['sqlite/real@1']['input'];
      readonly remoteId: CodecTypes['sqlite/text@1']['input'];
    };
  };
};
export type StorageColumnTypes = {
  readonly __unbound__: {
    readonly idempotent_actions: {
      readonly attempts: CodecTypes['sqlite/integer@1']['output'];
      readonly create_attempted: CodecTypes['sqlite/integer@1']['output'];
      readonly kind: CodecTypes['sqlite/text@1']['output'];
      readonly last_error: CodecTypes['sqlite/text@1']['output'] | null;
      readonly next_attempt: CodecTypes['sqlite/real@1']['output'];
      readonly payload: CodecTypes['sqlite/text@1']['output'];
      readonly remote_id: CodecTypes['sqlite/text@1']['output'] | null;
      readonly request_id: CodecTypes['sqlite/text@1']['output'];
      readonly response_json: CodecTypes['sqlite/text@1']['output'] | null;
      readonly state: CodecTypes['sqlite/text@1']['output'];
      readonly task_key: CodecTypes['sqlite/text@1']['output'] | null;
      readonly updated_at: CodecTypes['sqlite/text@1']['output'];
    };
    readonly kv: {
      readonly key: CodecTypes['sqlite/text@1']['output'];
      readonly value: CodecTypes['sqlite/text@1']['output'];
    };
    readonly meal_library: {
      readonly created_at: CodecTypes['sqlite/text@1']['output'];
      readonly id: CodecTypes['sqlite/text@1']['output'];
      readonly name: CodecTypes['sqlite/text@1']['output'];
      readonly position: CodecTypes['sqlite/integer@1']['output'];
    };
    readonly meal_slots: {
      readonly active: CodecTypes['sqlite/integer@1']['output'];
      readonly id: CodecTypes['sqlite/text@1']['output'];
      readonly name: CodecTypes['sqlite/text@1']['output'];
      readonly position: CodecTypes['sqlite/integer@1']['output'];
      readonly time: CodecTypes['sqlite/text@1']['output'];
      readonly time_aliases: CodecTypes['sqlite/text@1']['output'];
    };
    readonly project_task_cache: {
      readonly project_id: CodecTypes['sqlite/text@1']['output'];
      readonly remote_id: CodecTypes['sqlite/text@1']['output'] | null;
      readonly seen_at: CodecTypes['sqlite/real@1']['output'];
      readonly task_json: CodecTypes['sqlite/text@1']['output'];
      readonly task_key: CodecTypes['sqlite/text@1']['output'];
    };
    readonly task_tombstones: {
      readonly created_at: CodecTypes['sqlite/real@1']['output'];
      readonly remote_id: CodecTypes['sqlite/text@1']['output'];
    };
  };
};
export type StorageColumnInputTypes = {
  readonly __unbound__: {
    readonly idempotent_actions: {
      readonly attempts: CodecTypes['sqlite/integer@1']['input'];
      readonly create_attempted: CodecTypes['sqlite/integer@1']['input'];
      readonly kind: CodecTypes['sqlite/text@1']['input'];
      readonly last_error: CodecTypes['sqlite/text@1']['input'] | null;
      readonly next_attempt: CodecTypes['sqlite/real@1']['input'];
      readonly payload: CodecTypes['sqlite/text@1']['input'];
      readonly remote_id: CodecTypes['sqlite/text@1']['input'] | null;
      readonly request_id: CodecTypes['sqlite/text@1']['input'];
      readonly response_json: CodecTypes['sqlite/text@1']['input'] | null;
      readonly state: CodecTypes['sqlite/text@1']['input'];
      readonly task_key: CodecTypes['sqlite/text@1']['input'] | null;
      readonly updated_at: CodecTypes['sqlite/text@1']['input'];
    };
    readonly kv: {
      readonly key: CodecTypes['sqlite/text@1']['input'];
      readonly value: CodecTypes['sqlite/text@1']['input'];
    };
    readonly meal_library: {
      readonly created_at: CodecTypes['sqlite/text@1']['input'];
      readonly id: CodecTypes['sqlite/text@1']['input'];
      readonly name: CodecTypes['sqlite/text@1']['input'];
      readonly position: CodecTypes['sqlite/integer@1']['input'];
    };
    readonly meal_slots: {
      readonly active: CodecTypes['sqlite/integer@1']['input'];
      readonly id: CodecTypes['sqlite/text@1']['input'];
      readonly name: CodecTypes['sqlite/text@1']['input'];
      readonly position: CodecTypes['sqlite/integer@1']['input'];
      readonly time: CodecTypes['sqlite/text@1']['input'];
      readonly time_aliases: CodecTypes['sqlite/text@1']['input'];
    };
    readonly project_task_cache: {
      readonly project_id: CodecTypes['sqlite/text@1']['input'];
      readonly remote_id: CodecTypes['sqlite/text@1']['input'] | null;
      readonly seen_at: CodecTypes['sqlite/real@1']['input'];
      readonly task_json: CodecTypes['sqlite/text@1']['input'];
      readonly task_key: CodecTypes['sqlite/text@1']['input'];
    };
    readonly task_tombstones: {
      readonly created_at: CodecTypes['sqlite/real@1']['input'];
      readonly remote_id: CodecTypes['sqlite/text@1']['input'];
    };
  };
};

export namespace Models {
  export type IdempotentAction = {
    attempts: CodecTypes['sqlite/integer@1']['output'];
    createAttempted: CodecTypes['sqlite/integer@1']['output'];
    kind: CodecTypes['sqlite/text@1']['output'];
    lastError: CodecTypes['sqlite/text@1']['output'] | null;
    nextAttempt: CodecTypes['sqlite/real@1']['output'];
    payload: CodecTypes['sqlite/text@1']['output'];
    remoteId: CodecTypes['sqlite/text@1']['output'] | null;
    requestId: CodecTypes['sqlite/text@1']['output'];
    responseJson: CodecTypes['sqlite/text@1']['output'] | null;
    state: CodecTypes['sqlite/text@1']['output'];
    taskKey: CodecTypes['sqlite/text@1']['output'] | null;
    updatedAt: CodecTypes['sqlite/text@1']['output'];
    readonly [RelationKeys]?: never;
  };
  export type Kv = {
    key: CodecTypes['sqlite/text@1']['output'];
    value: CodecTypes['sqlite/text@1']['output'];
    readonly [RelationKeys]?: never;
  };
  export type MealLibraryEntry = {
    createdAt: CodecTypes['sqlite/text@1']['output'];
    id: CodecTypes['sqlite/text@1']['output'];
    name: CodecTypes['sqlite/text@1']['output'];
    position: CodecTypes['sqlite/integer@1']['output'];
    readonly [RelationKeys]?: never;
  };
  export type MealSlot = {
    active: CodecTypes['sqlite/integer@1']['output'];
    id: CodecTypes['sqlite/text@1']['output'];
    name: CodecTypes['sqlite/text@1']['output'];
    position: CodecTypes['sqlite/integer@1']['output'];
    time: CodecTypes['sqlite/text@1']['output'];
    timeAliases: CodecTypes['sqlite/text@1']['output'];
    readonly [RelationKeys]?: never;
  };
  export type ProjectTaskCache = {
    projectId: CodecTypes['sqlite/text@1']['output'];
    remoteId: CodecTypes['sqlite/text@1']['output'] | null;
    seenAt: CodecTypes['sqlite/real@1']['output'];
    taskJson: CodecTypes['sqlite/text@1']['output'];
    taskKey: CodecTypes['sqlite/text@1']['output'];
    readonly [RelationKeys]?: never;
  };
  export type TaskTombstone = {
    createdAt: CodecTypes['sqlite/real@1']['output'];
    remoteId: CodecTypes['sqlite/text@1']['output'];
    readonly [RelationKeys]?: never;
  };
}

export declare const models: {
  IdempotentAction: Models.IdempotentAction;
  Kv: Models.Kv;
  MealLibraryEntry: Models.MealLibraryEntry;
  MealSlot: Models.MealSlot;
  ProjectTaskCache: Models.ProjectTaskCache;
  TaskTombstone: Models.TaskTombstone;
};

export type TypeMaps = TypeMapsType<
  CodecTypes,
  QueryOperationTypes,
  FieldOutputTypes,
  FieldInputTypes,
  StorageColumnTypes,
  StorageColumnInputTypes,
  AggregateTypes
>;

type ContractBase = Omit<
  ContractType<{
    readonly namespaces: {
      readonly __unbound__: {
        readonly id: '__unbound__';
        readonly kind: 'sqlite-namespace';
        readonly entries: {
          readonly table: {
            readonly idempotent_actions: {
              columns: {
                readonly attempts: {
                  readonly nativeType: 'integer';
                  readonly codecId: 'sqlite/integer@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'sqlite/integer@1', 0>;
                  };
                };
                readonly create_attempted: {
                  readonly nativeType: 'integer';
                  readonly codecId: 'sqlite/integer@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'sqlite/integer@1', 0>;
                  };
                };
                readonly kind: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                };
                readonly last_error: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: true;
                };
                readonly next_attempt: {
                  readonly nativeType: 'real';
                  readonly codecId: 'sqlite/real@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'sqlite/real@1', 0>;
                  };
                };
                readonly payload: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                };
                readonly remote_id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: true;
                };
                readonly request_id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                };
                readonly response_json: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: true;
                };
                readonly state: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                };
                readonly task_key: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: true;
                };
                readonly updated_at: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
              };
              primaryKey: { readonly columns: readonly ['request_id'] };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly kv: {
              columns: {
                readonly key: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                };
                readonly value: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['key'] };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly meal_library: {
              columns: {
                readonly created_at: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                };
                readonly name: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                };
                readonly position: {
                  readonly nativeType: 'integer';
                  readonly codecId: 'sqlite/integer@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly meal_slots: {
              columns: {
                readonly active: {
                  readonly nativeType: 'integer';
                  readonly codecId: 'sqlite/integer@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'sqlite/integer@1', 1>;
                  };
                };
                readonly id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                };
                readonly name: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                };
                readonly position: {
                  readonly nativeType: 'integer';
                  readonly codecId: 'sqlite/integer@1';
                  readonly nullable: false;
                };
                readonly time: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                };
                readonly time_aliases: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'sqlite/text@1', '[]'>;
                  };
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly project_task_cache: {
              columns: {
                readonly project_id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                };
                readonly remote_id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: true;
                };
                readonly seen_at: {
                  readonly nativeType: 'real';
                  readonly codecId: 'sqlite/real@1';
                  readonly nullable: false;
                };
                readonly task_json: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                };
                readonly task_key: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['task_key'] };
              uniques: readonly [{ readonly columns: readonly ['remote_id'] }];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly task_tombstones: {
              columns: {
                readonly created_at: {
                  readonly nativeType: 'real';
                  readonly codecId: 'sqlite/real@1';
                  readonly nullable: false;
                };
                readonly remote_id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['remote_id'] };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
          };
        };
      };
    };
    readonly storageHash: StorageHash;
  }>,
  'roots' | 'domain'
> & {
  readonly target: 'sqlite';
  readonly targetFamily: 'sql';
  readonly roots: {
    readonly idempotent_actions: {
      readonly namespace: '__unbound__' & NamespaceId;
      readonly model: 'IdempotentAction';
    };
    readonly kv: { readonly namespace: '__unbound__' & NamespaceId; readonly model: 'Kv' };
    readonly meal_library: {
      readonly namespace: '__unbound__' & NamespaceId;
      readonly model: 'MealLibraryEntry';
    };
    readonly meal_slots: {
      readonly namespace: '__unbound__' & NamespaceId;
      readonly model: 'MealSlot';
    };
    readonly project_task_cache: {
      readonly namespace: '__unbound__' & NamespaceId;
      readonly model: 'ProjectTaskCache';
    };
    readonly task_tombstones: {
      readonly namespace: '__unbound__' & NamespaceId;
      readonly model: 'TaskTombstone';
    };
  };
  readonly domain: {
    readonly namespaces: {
      readonly __unbound__: {
        readonly models: {
          readonly IdempotentAction: {
            readonly fields: {
              readonly attempts: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/integer@1' };
              };
              readonly createAttempted: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/integer@1' };
              };
              readonly kind: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly lastError: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly nextAttempt: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/real@1' };
              };
              readonly payload: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly remoteId: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly requestId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly responseJson: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly state: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly taskKey: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: {
              readonly table: 'idempotent_actions';
              readonly namespaceId: '__unbound__';
              readonly fields: {
                readonly attempts: { readonly column: 'attempts' };
                readonly createAttempted: { readonly column: 'create_attempted' };
                readonly kind: { readonly column: 'kind' };
                readonly lastError: { readonly column: 'last_error' };
                readonly nextAttempt: { readonly column: 'next_attempt' };
                readonly payload: { readonly column: 'payload' };
                readonly remoteId: { readonly column: 'remote_id' };
                readonly requestId: { readonly column: 'request_id' };
                readonly responseJson: { readonly column: 'response_json' };
                readonly state: { readonly column: 'state' };
                readonly taskKey: { readonly column: 'task_key' };
                readonly updatedAt: { readonly column: 'updated_at' };
              };
            };
          };
          readonly Kv: {
            readonly fields: {
              readonly key: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly value: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: {
              readonly table: 'kv';
              readonly namespaceId: '__unbound__';
              readonly fields: {
                readonly key: { readonly column: 'key' };
                readonly value: { readonly column: 'value' };
              };
            };
          };
          readonly MealLibraryEntry: {
            readonly fields: {
              readonly createdAt: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly name: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly position: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/integer@1' };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: {
              readonly table: 'meal_library';
              readonly namespaceId: '__unbound__';
              readonly fields: {
                readonly createdAt: { readonly column: 'created_at' };
                readonly id: { readonly column: 'id' };
                readonly name: { readonly column: 'name' };
                readonly position: { readonly column: 'position' };
              };
            };
          };
          readonly MealSlot: {
            readonly fields: {
              readonly active: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/integer@1' };
              };
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly name: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly position: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/integer@1' };
              };
              readonly time: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly timeAliases: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: {
              readonly table: 'meal_slots';
              readonly namespaceId: '__unbound__';
              readonly fields: {
                readonly active: { readonly column: 'active' };
                readonly id: { readonly column: 'id' };
                readonly name: { readonly column: 'name' };
                readonly position: { readonly column: 'position' };
                readonly time: { readonly column: 'time' };
                readonly timeAliases: { readonly column: 'time_aliases' };
              };
            };
          };
          readonly ProjectTaskCache: {
            readonly fields: {
              readonly projectId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly remoteId: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly seenAt: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/real@1' };
              };
              readonly taskJson: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly taskKey: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: {
              readonly table: 'project_task_cache';
              readonly namespaceId: '__unbound__';
              readonly fields: {
                readonly projectId: { readonly column: 'project_id' };
                readonly remoteId: { readonly column: 'remote_id' };
                readonly seenAt: { readonly column: 'seen_at' };
                readonly taskJson: { readonly column: 'task_json' };
                readonly taskKey: { readonly column: 'task_key' };
              };
            };
          };
          readonly TaskTombstone: {
            readonly fields: {
              readonly createdAt: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/real@1' };
              };
              readonly remoteId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: {
              readonly table: 'task_tombstones';
              readonly namespaceId: '__unbound__';
              readonly fields: {
                readonly createdAt: { readonly column: 'created_at' };
                readonly remoteId: { readonly column: 'remote_id' };
              };
            };
          };
        };
      };
    };
  };
  readonly capabilities: {
    readonly sql: {
      readonly foreignKeys: true;
      readonly insertOnConflictSkip: true;
      readonly insertOnConflictWithoutTarget: true;
      readonly jsonAgg: true;
      readonly limit: true;
      readonly orderBy: true;
      readonly returning: true;
    };
  };
  readonly extensions: {};
  readonly meta: {};

  readonly profileHash: ProfileHash;
};

export type Contract = ContractWithTypeMaps<ContractBase, TypeMaps>;

export type Namespaces = Contract['storage']['namespaces'];
